SELECT a.AUTHOR_ID, a.AUTHOR_NAME, g.CATEGORY, g.TOTAL_SALES 
FROM 
(
    SELECT CATEGORY, AUTHOR_ID, SUM(SALES * PRICE) TOTAL_SALES
    FROM BOOK b, BOOK_SALES s
    WHERE b.BOOK_ID = s.BOOK_ID
    AND TO_CHAR(s.SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY CATEGORY, AUTHOR_ID
) g
JOIN AUTHOR a
ON g.AUTHOR_ID = a.AUTHOR_ID
ORDER BY 1 ASC, 3 DESC