SELECT CAR_ID, CAR_TYPE, FEE
FROM
(
    SELECT  C.CAR_ID,
            C.CAR_TYPE,
            FLOOR(C.DAILY_FEE * 30 *
            (100 - TO_NUMBER(REPLACE(P.DISCOUNT_RATE,'%',''))) / 100) AS FEE,
            ROW_NUMBER() OVER(
                PARTITION BY C.CAR_ID
                ORDER BY TO_NUMBER(REPLACE(P.DURATION_TYPE,'일 이상','')) DESC
            ) AS RN
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
      ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단','SUV')
      AND TO_NUMBER(REPLACE(P.DURATION_TYPE,'일 이상','')) <= 30
      AND C.CAR_ID NOT IN
      (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= DATE '2022-11-30'
            AND END_DATE >= DATE '2022-11-01'
      )
)
WHERE RN = 1
  AND FEE >= 500000
  AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;