SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO i
INNER JOIN 
(
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) r
ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%'
ORDER BY 6 DESC, 4 DESC