SELECT TO_CHAR(SALES_DATE, 'YYYY') YEAR, 
       TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH, 
       GENDER,
       COUNT(DISTINCT USER_ID) USERS
FROM 
(
    SELECT u.USER_ID, GENDER, SALES_DATE
    FROM USER_INFO u, ONLINE_SALE o
    WHERE u.USER_ID = o.USER_ID
) 
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER
HAVING GENDER IS NOT NULL
ORDER BY 1 ASC, 2 ASC, 3 ASC