SELECT 
    a.CAR_ID,
    CASE 
        WHEN TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE THEN '대여중'
        ELSE '대여 가능'
    END AVAILABILITY    
FROM 
(
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) a,
(
    SELECT CAR_ID, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
) b
WHERE a.CAR_ID = b.CAR_ID(+)
ORDER BY 1 DESC