SELECT HISTORY_ID, FLOOR(NVL(DISCOUNT_RATE, 1) * DAILY_FEE * DURATION) AS FEE
FROM
(
    SELECT A.HISTORY_ID, A.DAILY_FEE, A.DURATION, B.DURATION_TYPE, B.DISCOUNT_RATE,
           ROW_NUMBER() OVER (PARTITION BY A.HISTORY_ID ORDER BY B.DURATION_TYPE DESC) AS RN
    FROM
    (
    SELECT  A.CAR_ID, 
            B.HISTORY_ID, 
            A.CAR_TYPE, 
            A.DAILY_FEE, 
            B.END_DATE - B.START_DATE + 1 AS DURATION
      FROM  CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
     WHERE  A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭'
    ) A 
    LEFT JOIN (
    SELECT  CAR_TYPE, 
            TO_NUMBER(REPLACE(DURATION_TYPE, '일 이상', '')) AS DURATION_TYPE,
            (100 - TO_NUMBER(REPLACE(DISCOUNT_RATE,'%',''))) / 100 AS DISCOUNT_RATE
      FROM  CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    ) B 
    ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION >= B.DURATION_TYPE
)
WHERE RN = 1
ORDER BY 2 DESC, 1 DESC

-- SELECT COUNT(*) FROM (
-- SELECT      A.CAR_ID, 
--             B.HISTORY_ID, 
--             A.CAR_TYPE, 
--             A.DAILY_FEE, 
--             B.END_DATE - B.START_DATE + 1 AS DURATION
--       FROM  CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
--      WHERE  A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭'
--     )