SELECT a.aPNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a, PATIENT p, DOCTOR d
WHERE a.PT_NO = p.PT_NO AND a.MDDR_ID = d.DR_ID
AND a.APNT_CNCL_YN = 'N'
AND TO_CHAR(a.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
ORDER BY 6 ASC