SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_TIMESTAMP(TO_CHAR(DATETIME, 'HH24:MI'), 'HH24:MI') >= TO_TIMESTAMP('9:00', 'HH24:MI')
AND TO_TIMESTAMP(TO_CHAR(DATETIME, 'HH24:MI'), 'HH24:MI') <= TO_TIMESTAMP('19:59', 'HH24:MI')
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY 1;