
SELECT p.MEMBER_NAME, r.REVIEW_TEXT, TO_CHAR(r.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM
(
    SELECT MEMBER_ID
    FROM
    (
        SELECT MEMBER_ID, DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) rank
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )
    WHERE RANK = 1
) a
INNER JOIN MEMBER_PROFILE p
ON a.MEMBER_ID = p.MEMBER_ID
INNER JOIN REST_REVIEW r
ON p.MEMBER_ID = r.MEMBER_ID
ORDER BY 3, 2

