SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN TO_DATE('20220801', 'YYYYMMDD') AND TO_DATE('20221031', 'YYYYMMDD')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) 
AND START_DATE BETWEEN TO_DATE('20220801', 'YYYYMMDD') AND TO_DATE('20221031', 'YYYYMMDD')
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
HAVING COUNT(*) <> 0
ORDER BY 1, 2 DESC