SELECT DISTINCT r.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR r, CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE r.CAR_ID = h.CAR_ID
    AND r.CAR_TYPE = '세단'
    AND TO_CHAR(h.START_DATE, 'YYYY-MM') LIKE '%10%'
ORDER BY 1 DESC