SELECT ('/home/grep/src/' || b.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE f
JOIN (
    SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY 2 DESC
    FETCH FIRST 1 ROWS ONLY
) b
ON f.BOARD_ID = b.BOARD_ID
ORDER BY FILE_ID DESC